### ISSUE TITLE
correlation id missing when trying to communicate between different rabbitmq rpc library

### ISSUE THREAD

**Issue by campanagerald** [tjmehta/amqplib-rpc#18]
I am using spring amqp for my service written in Java, and my colleague created a service using nodejs and he is using amqplib-rpc. The problem is when I tried to request from spring amqp to amqplib-rpc it raise an error that "reply() cannot reply to a message without 'correlationId'". It said that spring amqp automatically creates a correlationid. In fact, its ok when I use spring amqp to spring amqp request

**Comment by tjmehta** [comment]
Interesting, I haven’t used spring amqp. Does spring amqp have an API for RPC or is he just creating a message?

**Comment by campanagerald** [comment]
Thanks. :) 

I'm not sure, I followed the tutorial here https://www.rabbitmq.com/tutorials/tutorial-six-spring-amqp.html

I log the message from your reply() method, the result is the correlationId is undefined

**Comment by tjmehta** [comment]
Can you log `message.properties`? Maybe they are using a different casing
for “correlationId”

**Comment by campanagerald** [comment]
this is the content of the message

{ fields: 
   { consumerTag: 'amq.ctag-pWkDuqi5hdwByLbOHeLrxA',
     deliveryTag: 1,
     redelivered: false,
     exchange: '',
     routingKey: 'spring.to.node' },
  properties: 
   { contentType: 'text/plain',
     contentEncoding: 'UTF-8',
     headers: {},
     deliveryMode: 2,
     priority: 0,
     correlationId: undefined,
     replyTo: 'amq.rabbitmq.reply-to.g2dkABNyYWJiaXRAcmFiYml0bXEtc3J2AABkoQAAAAcD.CTev4IP5OKl7fAC8WDoAvw==',
     expiration: undefined,
     messageId: undefined,
     timestamp: undefined,
     type: undefined,
     userId: undefined,
     appId: undefined,
     clusterId: undefined },
  content: <Buffer 68 65 6c 6c 6f> }

**Comment by campanagerald** [comment]
I already raised an issue to https://github.com/spring-projects/spring-amqp/issues/657

**Comment by tjmehta** [comment]
Interesting, yeah I don't know much about the spring API. I might take a look this weekend, but let's see how they respond

**Comment by campanagerald** [comment]
Thanks :+1:

**Comment by campanagerald** [comment]
The other one said that amqplib-rpc does not support Direct reply-to.

**Comment by campanagerald** [comment]
sir, how's the progress of this issue?

**Comment by tjmehta** [comment]
That makes sense, want to make a PR? You can remove the [assertion](https://github.com/tjmehta/amqplib-rpc/blob/master/lib/reply.js#L31) and only add `correlationId` to `opts` [when it exists](https://github.com/tjmehta/amqplib-rpc/blob/master/lib/reply.js#L47) (use `const exists = require('101/exists')`).

**Comment by campanagerald** [comment]
Can you guide me how to make a pull request?

**Comment by campanagerald** [comment]
sir, your solution is correct, i tried to remove the assert(correlationId, "reply() cannot reply to a message without 'correlationId'") and it works.

**Comment by campanagerald** [comment]
don't need to PR. just remove the assertion to correlation id

**Comment by tjmehta** [comment]
Cool Ill PR the same then, should have it done in the next hour
